// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
)

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT e.event_id, e.description, e.created_at
FROM events e
JOIN slugs s ON s.event_id = e.event_id
WHERE s.slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(&i.EventID, &i.Description, &i.CreatedAt)
	return i, err
}

const getQuestionByEventAndIndex = `-- name: GetQuestionByEventAndIndex :one
SELECT question_id, event_id, big_text, small_text, image_filename, choice_a, choice_b
FROM questions
WHERE event_id = $1
ORDER BY question_id ASC
LIMIT 1 OFFSET $2 - 1
`

type GetQuestionByEventAndIndexParams struct {
	EventID       string      `json:"event_id"`
	QuestionIndex interface{} `json:"question_index"`
}

func (q *Queries) GetQuestionByEventAndIndex(ctx context.Context, arg GetQuestionByEventAndIndexParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByEventAndIndex, arg.EventID, arg.QuestionIndex)
	var i Question
	err := row.Scan(
		&i.QuestionID,
		&i.EventID,
		&i.BigText,
		&i.SmallText,
		&i.ImageFilename,
		&i.ChoiceA,
		&i.ChoiceB,
	)
	return i, err
}

const listQuestionsByEventID = `-- name: ListQuestionsByEventID :many
SELECT question_id, event_id, big_text, small_text, image_filename, choice_a, choice_b
FROM questions
WHERE event_id = $1
ORDER BY question_id ASC
`

func (q *Queries) ListQuestionsByEventID(ctx context.Context, eventID string) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.QuestionID,
			&i.EventID,
			&i.BigText,
			&i.SmallText,
			&i.ImageFilename,
			&i.ChoiceA,
			&i.ChoiceB,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
