// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Event struct {
	EventID     string    `json:"event_id"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Question struct {
	QuestionID    string `json:"question_id"`
	EventID       string `json:"event_id"`
	BigText       string `json:"big_text"`
	SmallText     string `json:"small_text"`
	ImageFilename string `json:"image_filename"`
	ChoiceA       string `json:"choice_a"`
	ChoiceB       string `json:"choice_b"`
}

type Response struct {
	QuestionID string    `json:"question_id"`
	SessionID  string    `json:"session_id"`
	Slug       string    `json:"slug"`
	Choice     string    `json:"choice"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Session struct {
	SessionID string         `json:"session_id"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Mobile    sql.NullString `json:"mobile"`
}

type Slug struct {
	Slug      string    `json:"slug"`
	EventID   string    `json:"event_id"`
	CreatedAt time.Time `json:"created_at"`
}
