// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses.sql

package database

import (
	"context"
)

const getResponseByQuestionAndSession = `-- name: GetResponseByQuestionAndSession :one
SELECT question_id, session_id, slug, choice, created_at, updated_at
FROM responses
WHERE question_id = $1 AND session_id = $2
`

type GetResponseByQuestionAndSessionParams struct {
	QuestionID string `json:"question_id"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) GetResponseByQuestionAndSession(ctx context.Context, arg GetResponseByQuestionAndSessionParams) (Response, error) {
	row := q.db.QueryRowContext(ctx, getResponseByQuestionAndSession, arg.QuestionID, arg.SessionID)
	var i Response
	err := row.Scan(
		&i.QuestionID,
		&i.SessionID,
		&i.Slug,
		&i.Choice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResponsesBySessionAndEvent = `-- name: GetResponsesBySessionAndEvent :many
SELECT r.question_id, r.session_id, r.slug, r.choice, r.created_at, r.updated_at
FROM responses r
JOIN questions q ON q.question_id = r.question_id
WHERE r.session_id = $1 AND q.event_id = $2
`

type GetResponsesBySessionAndEventParams struct {
	SessionID string `json:"session_id"`
	EventID   string `json:"event_id"`
}

func (q *Queries) GetResponsesBySessionAndEvent(ctx context.Context, arg GetResponsesBySessionAndEventParams) ([]Response, error) {
	rows, err := q.db.QueryContext(ctx, getResponsesBySessionAndEvent, arg.SessionID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Response{}
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.QuestionID,
			&i.SessionID,
			&i.Slug,
			&i.Choice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertResponse = `-- name: UpsertResponse :one
INSERT INTO responses (question_id, session_id, slug, choice, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (question_id, session_id)
DO UPDATE SET
    choice = EXCLUDED.choice,
    slug = EXCLUDED.slug,
    updated_at = NOW()
RETURNING question_id, session_id, slug, choice, created_at, updated_at
`

type UpsertResponseParams struct {
	QuestionID string `json:"question_id"`
	SessionID  string `json:"session_id"`
	Slug       string `json:"slug"`
	Choice     string `json:"choice"`
}

func (q *Queries) UpsertResponse(ctx context.Context, arg UpsertResponseParams) (Response, error) {
	row := q.db.QueryRowContext(ctx, upsertResponse,
		arg.QuestionID,
		arg.SessionID,
		arg.Slug,
		arg.Choice,
	)
	var i Response
	err := row.Scan(
		&i.QuestionID,
		&i.SessionID,
		&i.Slug,
		&i.Choice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
