// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
)

const getSession = `-- name: GetSession :one
SELECT session_id, name, email, mobile FROM sessions WHERE session_id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, sessionID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.Name,
		&i.Email,
		&i.Mobile,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (session_id, name, email, mobile)
VALUES ($1, $2, $3, $4)
ON CONFLICT (session_id) 
DO UPDATE SET 
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    mobile = EXCLUDED.mobile
RETURNING session_id, name, email, mobile
`

type UpsertSessionParams struct {
	SessionID string         `json:"session_id"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Mobile    sql.NullString `json:"mobile"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, upsertSession,
		arg.SessionID,
		arg.Name,
		arg.Email,
		arg.Mobile,
	)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.Name,
		&i.Email,
		&i.Mobile,
	)
	return i, err
}
